vim.cmd('set relativenumber')
vim.cmd('set number numberwidth=9')
vim.cmd('set numberwidth=1')
vim.cmd('set signcolumn=no')
vim.cmd('set tabstop=4') --tab is 4 spaces
vim.cmd('set path+=**')
vim.cmd('set softtabstop=0')
vim.cmd('set noexpandtab')
vim.cmd('set shiftwidth=4')
-- vim.cmd('set colorcolumn=80')
vim.cmd('set cmdheight=0')
