-- Function to create the highlight command
local function create_cmd(scope, settings)
    local guifg = settings.foreground and "guifg=" .. settings.foreground or ""
    local guibg = settings.background and "guibg=" .. settings.background or ""
    local guisp = settings.special and "guisp=" .. settings.special or ""
    local gui = settings.fontStyle and "gui=" .. settings.fontStyle or ""

    local options = { guifg, guibg, guisp, gui }
    local cmd_parts = {}
    for _, option in ipairs(options) do
        if option ~= "" then
            table.insert(cmd_parts, option)
        end
    end

    return string.format("highlight %s %s", scope, table.concat(cmd_parts, " "))
end

-- Color definitions
local colors = {
    activityBar_activeBackground = "#000000",
    activityBar_activeBorder = "#707070",
    activityBar_background = "#000000",
    activityBar_border = "#707070",
    activityBar_foreground = "#e1e4e8",
    activityBar_inactiveForeground = "#6a737d",
    activityBarBadge_background = "#0366d6",
    activityBarBadge_foreground = "#ffffff",
    badge_background = "#044289",
    badge_foreground = "#c8e1ff",
    breadcrumb_activeSelectionForeground = "#d1d5da",
    breadcrumb_background = "#000000",
    breadcrumb_focusForeground = "#e1e4e8",
    breadcrumb_foreground = "#959da5",
    breadcrumbPicker_background = "#2b3036",
    button_foreground = "#dcffe4",
    checkbox_background = "#444d56",
    editorInlayHint_background = "#2b3036",
    editorInlayHint_foreground = "#959da5",
    checkbox_border = "#1b1f23",
    contrastBorder = "#707070",
    debugToolBar_background = "#2b3036",
    descriptionForeground = "#959da5",
    diffEditor_insertedTextBackground = "#28a74530",
    diffEditor_removedTextBackground = "#d73a4930",
    dropdown_background = "#0d1117",
    dropdown_border = "#1b1f23",
    dropdown_foreground = "#e1e4e8",
    editor_background = "#0a0d12",
    editor_focusedStackFrameHighlightBackground = "#bb880088",
    editor_foldBackground = "#282e33",
    editor_foreground = "#e1e4e8",
    editor_lineHighlightBackground = "#000000",
    editor_lineHighlightBorder = "#fb863283",
    editor_selectionHighlightBackground = "#17e5e633",
    editor_selectionHighlightBorder = "#17e5e600",
    editor_stackFrameHighlightBackground = "#aa770077",
    editor_wordHighlightBackground = "#17e5e600",
    editor_wordHighlightBorder = "#17e5e699",
    editor_wordHighlightStrongBackground = "#17e5e600",
    editor_wordHighlightStrongBorder = "#17e5e666",
    editorBracketMatch_background = "#17e5e650",
    editorBracketMatch_border = "#17e5e600",
    editorCursor_foreground = "#c8e1ff",
    editorGroup_border = "#1b1f23",
    editorGroupHeader_tabsBackground = "#000000",
    editorGroupHeader_tabsBorder = "#000000",
    editorGutter_addedBackground = "#28a745",
    editorGutter_deletedBackground = "#ea4a5a",
    editorGutter_modifiedBackground = "#2188ff",
    editorIndentGuide_activeBackground = "#444d56",
    editorIndentGuide_background = "#2f363d",
    editorLineNumber_activeForeground = "#e1e4e8",
    editorLineNumber_foreground = "#444d56",
    editorOverviewRuler_border = "#1b1f23",
    editorWhitespace_foreground = "#444d56",
    editorWidget_background = "#1f2428",
    errorForeground = "#f97583",
    focusBorder = "#79c0ff",
    foreground = "#d1d5da",
    gitDecoration_addedResourceForeground = "#34d058",
    gitDecoration_conflictingResourceForeground = "#ffab70",
    gitDecoration_deletedResourceForeground = "#ea4a5a",
    gitDecoration_ignoredResourceForeground = "#6a737d",
    gitDecoration_modifiedResourceForeground = "#79b8ff",
    gitDecoration_submoduleResourceForeground = "#6a737d",
    gitDecoration_untrackedResourceForeground = "#34d058",
    input_background = "#000000",
    input_border = "#707070",
    input_foreground = "#e1e4e8",
    input_placeholderForeground = "#959da5",
    list_activeSelectionBackground = "#39414a",
    list_activeSelectionForeground = "#e1e4e8",
    list_focusBackground = "#044289",
    list_hoverBackground = "#282e34",
    list_hoverForeground = "#e1e4e8",
    list_inactiveFocusBackground = "#1d2d3e",
    list_inactiveSelectionBackground = "#171e27",
    list_inactiveSelectionForeground = "#e1e4e8",
    notificationCenterHeader_background = "#24292e",
    notificationCenterHeader_foreground = "#959da5",
    notifications_border = "#1b1f23",
    notifications_foreground = "#e1e4e8",
    notificationsErrorIcon_foreground = "#ea4a5a",
    notificationsInfoIcon_foreground = "#79b8ff",
    notificationsWarningIcon_foreground = "#ffab70",
    panel_background = "#000000",
    panel_border = "#707070",
    panelInput_border = "#2f363d",
    panelTitle_activeBorder = "#79c0ff",
    panelTitle_activeForeground = "#e1e4e8",
    panelTitle_inactiveForeground = "#959da5",
    peekViewEditor_background = "#1f242888",
    peekViewEditor_matchHighlightBackground = "#ffd33d33",
    peekViewResult_background = "#1f2428",
    peekViewResult_matchHighlightBackground = "#ffd33d33",
    pickerGroup_border = "#444d56",
    pickerGroup_foreground = "#e1e4e8",
    progressBar_background = "#0366d6",
    quickInput_background = "#040507",
    quickInput_foreground = "#e1e4e8",
    scrollbar_shadow = "#000",
    scrollbarSlider_activeBackground = "#6a737d88",
    scrollbarSlider_background = "#6a737d33",
    scrollbarSlider_hoverBackground = "#6a737d44",
    selection_background = "#008000",
    settings_headerForeground = "#e1e4e8",
    settings_modifiedItemIndicator = "#0366d6",
    sideBar_background = "#040507",
    sideBar_border = "#707070",
    sideBar_foreground = "#d1d5da",
    sideBarSectionHeader_background = "#000000",
    sideBarSectionHeader_border = "#1b1f23",
    sideBarSectionHeader_foreground = "#e1e4e8",
    sideBarTitle_foreground = "#e1e4e8",
    statusBar_background = "#000000",
    statusBar_border = "#707070",
    statusBar_debuggingBackground = "#931c06",
    statusBar_debuggingForeground = "#ffffff",
    statusBar_foreground = "#d1d5da",
    statusBar_noFolderBackground = "#24292e",
    statusBarItem_prominentBackground = "#282e34",
    tab_activeBackground = "#000000",
    tab_activeBorder = "#24292e",
    tab_activeBorderTop = "#79c0ff",
    tab_activeForeground = "#e1e4e8",
    tab_border = "#707070",
    tab_hoverBackground = "#24292e",
    tab_inactiveBackground = "#000000",
    tab_inactiveForeground = "#959da5",
    tab_unfocusedActiveBorder = "#24292e",
    tab_unfocusedActiveBorderTop = "#1b1f23",
    tab_unfocusedHoverBackground = "#24292e",
    terminal_background = "#040507",
    terminal_border = "#707070",
    terminal_foreground = "#d1d5da",
    textBlockQuote_background = "#24292e",
    textBlockQuote_border = "#444d56",
    textCodeBlock_background = "#2f363d",
    textLink_activeForeground = "#c8e1ff",
    textLink_foreground = "#79b8ff",
    textPreformat_foreground = "#d1d5da",
    textSeparator_foreground = "#586069",
    titleBar_activeBackground = "#000000",
    titleBar_activeForeground = "#e1e4e8",
    titleBar_border = "#1b1f23",
    titleBar_inactiveBackground = "#000000",
    titleBar_inactiveForeground = "#959da5",
    tree_indentGuidesStroke = "#2f363d",
    welcomePage_buttonBackground = "#2f363d",
    welcomePage_buttonHoverBackground = "#444d56",
    button_background = "#044289",
    button_hoverBackground = "#0366d6",
    dropdown_listBackground = "#24292e",
    editor_findMatchBackground = "#ffffff3e",
    editor_findMatchBorder = "#0366d6",
    editor_findMatchHighlightBackground = "#d1cfcf3e",
    editor_inactiveSelectionBackground = "#707070",
    editor_selectionBackground = "#d1d5da",
    notifications_background = "#000",
    notificationToast_border = "#586069",
    window_activeBorder = "#000",
}

-- Apply the colors
for color, value in pairs(colors) do
    local cmd = create_cmd(color, { foreground = value })
    vim.cmd(cmd)
end

-- Set the statusline color to gray
--vim.cmd("highlight StatusLine guibg=yellow guifg=#ffffff")

-- Set the background color to pitch black
--vim.cmd("highlight Normal guibg=black guifg=pink")
